name: Falcon Hybrid Analysis Scan

on:
  repository_dispatch:
    types: [falcon-scan-request]

jobs:
  scan-pdf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(github.event.client_payload.pdf_files) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download PDF
        run: |
          mkdir -p scanned-pdfs
          cp "${{ matrix.file }}" scanned-pdfs/

      - name: Upload PDF to Falcon Hybrid Analysis
        id: hybrid
        run: |
          response=$(curl -s -X POST "https://www.hybrid-analysis.com/api/v2/submit/file" \
            -H "api-key: ${{ secrets.HYBRID_ANALYSIS_API_KEY }}" \
            -H "User-Agent: Falcon Sandbox" \
            -F "file=@${{ matrix.file }}" \
            -F "environment_id=120") # Windows 10

          echo "$response" > "results-${{ matrix.file }}.json"
          url=$(echo "$response" | jq -r '.environment_url')
          threat_score=$(echo "$response" | jq -r '.threat_score')
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "threat_score=$threat_score" >> $GITHUB_OUTPUT

      - name: Upload Hybrid Analysis Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hybrid-analysis-${{ matrix.file }}
          path: results-${{ matrix.file }}.json

      - name: Dispatch Gemini Conversion if Clean
        if: ${{ steps.hybrid.outputs.threat_score < 70 }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: gemini-convert-request
          client-payload: |
            {
              "file": "${{ matrix.file }}",
              "sha": "${{ github.event.client_payload.sha }}"
            }
