name: Falcon Hybrid Analysis Scan

on:
  repository_dispatch:
    types: [falcon-scan-request]

jobs:
  scan-pdf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(github.event.client_payload.pdf_files) }}

    steps:
      - name: Download file from repo
        uses: actions/checkout@v3

      - name: Upload file to Falcon Hybrid Analysis
        id: hybrid
        run: |
          response=$(curl -s -X POST "https://www.hybrid-analysis.com/api/v2/submit/file" \
            -H "api-key: ${{ secrets.HYBRID_ANALYSIS_API_KEY }}" \
            -H "User-Agent: Falcon Sandbox" \
            -F "file=@${{ matrix.file }}" \
            -F "environment_id=120") # Windows 10
          echo "url=$(echo "$response" | jq -r '.environment_url')" >> $GITHUB_OUTPUT
          echo "threat_score=$(echo "$response" | jq -r '.threat_score')" >> $GITHUB_OUTPUT

      - name: Upload analysis results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hybrid-analysis-${{ matrix.file }}
          path: |
            hybrid-analysis-results-${{ matrix.file }}.json
        run: |
          echo "${{ steps.hybrid.outputs.response }}" > hybrid-analysis-results-${{ matrix.file }}.json

      - name: Dispatch Gemini Conversion if clean
        if: ${{ steps.hybrid.outputs.threat_score < 70 }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: gemini-convert-request
          client-payload: |
            {
              "file": "${{ matrix.file }}",
              "sha": "${{ github.event.client_payload.sha }}"
            }
