name: PDF Detection

on:
  push:
    branches:
      - development
    paths:
      - 'Annual Security Reports/**.pdf'

jobs:
  detect-new-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Get list of added PDF files
        id: get_pdfs
        run: |
          echo "files=$(git diff-tree --no-commit-id --name-status -r ${{ github.sha }} | grep '^A' | grep '.pdf$' | awk '{print $2}' | jq -R -s -c 'split("\n") | map(select(. != ""))')" >> $GITHUB_OUTPUT

      - name: Dispatch Scan Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: falcon-scan-request
          client-payload: |
            {
              "pdf_files": ${{ steps.get_pdfs.outputs.files }},
              "sha": "${{ github.sha }}"
            }
